---
- name: Deploy Vite App
  hosts: localhost
  become: true

  tasks:
    - name: Pull latest code
      git:
        repo: https://github.com/SarveshN07/Quizz_Master.git
        dest: ~/vite-deploy
        version: main
        force: yes

    - name: Build Docker image
      command: docker build -t vite-app .
      args:
        chdir: ~/vite-deploy

    - name: Stop and remove old container (if exists)
      shell: |
        docker stop vite-app && docker rm vite-app
      ignore_errors: true

    - name: Prune old images
      command: docker image prune -f

    - name: Run new container
      command: docker run -d -p 3000:4713 --name vite-app vite-app

    - name: Wait for the app
      wait_for:
        port: 3000
        delay: 3
