// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bbfxiszxchpkujalzztx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJiZnhpc3p4Y2hwa3VqYWx6enR4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxNzA5MTUsImV4cCI6MjA2Mzc0NjkxNX0.3cx14UzlnpfglKXvEonpG0LIRyHzU-QcV35ifha249k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);